### ISSUE TITLE
module 'awsgi' has no attribute 'response'

### ISSUE THREAD

**Issue by revmischa** [slank/awsgi#11]
```
File "/var/task/index.py", line 7, in lambda_handler
return awsgi.response(app, event, context)
AttributeError: module 'awsgi' has no attribute 'response'
```

**Comment by revmischa** [comment]
ugh wrong pip package

**Comment by chiju** [comment]
which is the correct package, I am also getting the same error in aws lamda, code is 

import awsgi
from flask import Flask, request, jsonify
import json

app = Flask(__name__)

@app.route('/')
def index():
	return {
      'statusCode': 200,
      'body': json.dumps('Hello World!')
  }

def lambda_handler(event, context):
	return awsgi.response(app, event, context)

**Comment by chadawagner** [comment]
`aws-wsgi`
