### ISSUE TITLE
Pass raw AWS Lambda event via the WSGI environ dictionary

### ISSUE THREAD

**Issue by jordal** [slank/awsgi#17]
I've been happily using `awsgi` until encountering an issue when using API Gateway [custom authorizers.](https://docs.aws.amazon.com/apigateway/latest/developerguide/use-custom-authorizer.html#api-gateway-custom-authorizer-input) The authorizer context, which allows your authorizer to pass custom data to the application (e.g. user ID, group membership, permissions, etc.), exists as a dictionary value in the Lambda event. It lives in `event['requestContext']['authorizer']`, but this value is not passed by `awsgi` to the application.

Since AWS could at any time add other bits of useful metadata to the Lambda event, would it make sense for `awsgi` to just pass the AWS Lambda event to the application via the WSGI environ dictionary?

**Comment by slank** [comment]
Fixed by #22 

Thanks for the report @jordal
