### ISSUE TITLE
Base path mapping of API GW custom domains is added to path

### ISSUE THREAD

**Issue by revmischa** [slank/awsgi#18]
I'm not sure what the proper solution for this is but,
If you set up custom API gateway domain with a base path mapping, then the path mapping and stage are added to the path flask receives. So instead of it dispatching on /foo/bar it dispatches on /v1/Prod/foo/bar.

<img width="402" alt="screen shot 2018-04-29 at 14 35 56" src="https://user-images.githubusercontent.com/245131/39406182-edda8cd8-4bba-11e8-89b0-102069732ce8.png">

If I go to https://qanda.llolo.lol/v1/Prod/foo/bar - then I get a 404 because it tries to send it to /v1/Prod/foo/bar instead of /foo/bar.

What's the best way to deal with this?

**Comment by slank** [comment]
@revmischa sorry, I don't have a solution. I hope you were able to figure it out.
