### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by frob** [slank/awsgi#21]
There seems to be something lacking in either the API-Gateway setup docs or the awsgi docs. I have copied the code directly from the example and I cannot get it to work. I am using the aws sam cli for testing. I can get the generic un-styled Flask 404 response but nothing else. 

As far as I can tell the lambda handler is handling, but the request is never handed to flask.

**Comment by jolo-dev** [comment]
Yes, I also would like to know, how to deploy it.

**Comment by rooby** [comment]
Also missing for the documentation is an example of accessing the raw lambda event & context objects from within an app route.
