### ISSUE TITLE
Missing wsgi.url_scheme

### ISSUE THREAD

**Issue by astronouth7303** [slank/awsgi#29]
Flask seems to require `wsgi.url_scheme` in the WSGI environ dict.

```
[ERROR] KeyError: 'wsgi.url_scheme'
Traceback (most recent call last):
  File "/var/task/__main__.py", line 17, in main
    return awsgi.response(app, event, context, base64_content_types={"image/png"})
  File "/var/task/awsgi/__init__.py", line 26, in response
    output = app(environ(event, context), sr)
  File "/var/task/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/task/flask/app.py", line 2441, in wsgi_app
    ctx = self.request_context(environ)
  File "/var/task/flask/app.py", line 2358, in request_context
    return RequestContext(self, environ)
  File "/var/task/flask/ctx.py", line 292, in __init__
    self.url_adapter = app.create_url_adapter(self.request)
  File "/var/task/flask/app.py", line 2173, in create_url_adapter
    subdomain=subdomain,
  File "/var/task/werkzeug/routing.py", line 1502, in bind_to_environ
    wsgi_server_name = get_host(environ).lower()
  File "/var/task/werkzeug/wsgi.py", line 170, in get_host
    if (environ["wsgi.url_scheme"], environ["SERVER_PORT"]) not in (
```

This is in violation of [PEP 3333](https://www.python.org/dev/peps/pep-3333/#environ-variables):

> In addition to the CGI-defined variables, the environ dictionary ... must contain the following WSGI-defined variables:

**Comment by slank** [comment]
Hi, @astronouth7303. I don't think there's anything I can do to fix this in awsgi. It might be more fruitful to file this bug report in the [werkzeug](https://github.com/pallets/werkzeug) project. That appears to be where the exception is happening.

**Comment by astronouth7303** [comment]
As per my comment, this is a perfectly reasonable thing for werkzeug to expect because it is a mandatory part of the WSGI v1.0.1 specification, as laid out in PEP 3333.

In addition, it was also part of the WSGI v1.0 specification, as laid out in PEP 333.

**Comment by astronouth7303** [comment]
The `x-forwarded-proto` header might be helpful.

**Comment by slank** [comment]
Aha! I understand now. I was reading the pronouns the wrong way round thinking you meant that Flask was wrong.

`awsgi` _does_ set that variable from `x-forwarded-proto`, but it _does not_ set the variable otherwise. The PEP isn't as clear what value should be used `wsgi.url_scheme` is unknown as it is for the CGI variables, but it does provide a sample implementation considered valid for purpose. I'll just need to translate that into APIGW and I'll have a fix up for review.

**Comment by slank** [comment]
Well, there's just no equivalent in the API Gateway proxy integration request that indicates the protocol. The only reasonable thing to do is set it to an empty string, which I've done in PR#30.

It appears this will [make werkzeug happy](https://github.com/pallets/werkzeug/blob/master/src/werkzeug/wsgi.py#L169), but I'm not sure this is what the PEP intended.

**Comment by astronouth7303** [comment]
The pep is actually vague about acceptable values for that value. I'm guessing most libraries will just blindly use it in url reconstruction?

**Comment by slank** [comment]
That's what I'm worried about. I don't know if it's better to leave the value out (which breaks werkzeug), set it to an empty string, or set it to None. I feel like empty string is most compliant for your use-case, but I feel like having it unset is more correct.

**Comment by astronouth7303** [comment]
Well, so far the only time I've seen it is the ELB Healthcheck, ie not a real request, so you could just blatently lie and set it to `http` and it'll probably be ok?

**Comment by slank** [comment]
I don't like that either because it could cause a problem with applications that require HTTPS. APIGW _only_ speaks HTTPS so that wouldn't be correct anyway.

**Comment by astronouth7303** [comment]
#30 looks like it was going to fix this but it was never merged?

**Comment by slank** [comment]
Hmm. I don't know what happened but I've pushed the change and bumped the version.

**Comment by astronouth7303** [comment]
Could you upload the bumped version to PyPI?

**Comment by slank** [comment]
I had a typo, caught by the tests. Fix has built and been updated in PyPI
