### ISSUE TITLE
Error with sending .zip file with send_file

### ISSUE THREAD

**Issue by Kurtuozan** [slank/awsgi#40]
Hi,
I want to create a dummy .zip file and send the response with the function send_file. 

        memory_file = BytesIO()
        with zipfile.ZipFile(memory_file, 'w') as zf:
            zipinfo = zipfile.ZipInfo("test")
            zipinfo.date_time = time.localtime(time.time())[:6]
            zipinfo.compress_type = zipfile.ZIP_DEFLATED
            zf.writestr(zipinfo, "this is test zip content")
        memory_file.seek(0)
        return send_file(memory_file, attachment_filename='capsule.zip', as_attachment=True)

To see if the .zip file is processed and sent correctly I send the GET request via my browser.
The .zip file is sent, i download it but when I want to see the archive of the .zip I cannot because the .zip file is corrupted.

I updated the line 41 in the __init__.py file 

        self.base64_content_types = set(base64_content_types or ["application/zip"]) or set()

I also tried doing the same thing without using AWSGI (using only python FlaskRESTful) and i had no issues.

Could you help me resolving this issue
Thanks

**Comment by slank** [comment]
Hi, @Kurtuozan. I haven't investigated this yet, but I wanted to check: are you setting a `Content-Type: application/zip` header in your response?

**Comment by Kurtuozan** [comment]
Hi @slank,
No I didn't put the header Content-Type: application/zip.
I tried it now: 

        memory_file = BytesIO()
        with zipfile.ZipFile(memory_file, 'w') as zf:
            zipinfo = zipfile.ZipInfo("test")
            zipinfo.date_time = time.localtime(time.time())[:6]
            zipinfo.compress_type = zipfile.ZIP_DEFLATED
            zf.writestr(zipinfo, "this is test zip content")
        memory_file.seek(0)
        return {
            'headers': {'Content-Type: application/zip'},
            'body': send_file(memory_file, attachment_filename='capsule.zip', as_attachment=True)
        }

When I send the request via my browser now I don't get the automatic download or any download.
I get this line in my browser eyJtZXNzYWdlIjogIkludGVybmFsIFNlcnZlc.
When I go look into the developer tools inside the tab i called the request i can see that Response Header of the response is: 

Content-Length: 37
Content-Type: application/json
Date: Thu, 26 Sep 2019 07:24:26 GMT
Server: Werkzeug/0.15.5 Python/3.7.4

I just want to add that when i don't put the header content type and i call it like this 

return  send_file(memory_file, attachment_filename='capsule.zip', as_attachment=True)

I get the corrupted .zip file

**Comment by slank** [comment]
Hi, @Kurtuozan. When I base64 decode that value (`eyJtZXNzYWdlIjogIkludGVybmFsIFNlcnZlc`), I get what appears to be an error message: `{"message": "Internal Serve`

I think your original method was correct; no need to set the content type. What are you doing with the response you get from the server? Could the "corrupt" zip data actually be base64 encoded?

**Comment by Kurtuozan** [comment]
Hi, @slank 
So the situation is that when I download the corrupted dummy.zip and I go into the terminal and run the command :
**cat dummy.zip**
I get a very long base64 encoded string. And when i decode that string and write it in a new file in linux: that file becomes not corrupted and I can extract the initial file that i wanted.

How can I overcome this issue so I don't have to decode it after i download the dummy.zip
Thank you for your help :)

**Comment by slank** [comment]
Right. That makes sense. I apologize that I only have questions and not answers, but I'm hoping I can lead you in the right direction sooner than I could investigate myself.

I see that there is a transfer-encoding header we maybe should be setting.
https://www.w3.org/Protocols/rfc1341/5_Content-Transfer-Encoding.html

I think it's probably needed in AWSGI but I'm not super confident. Have you tried this with Flask locally, without AWSGI?

**Comment by slank** [comment]
@Kurtuozan OK, so a colleague pointed me at this page about configuring content type handling in APIGW.
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html

Are you using awsgi with APIGW or with ALB? Hopefully the former, and hopefully that link helps.

**Comment by Kurtuozan** [comment]
Hi @slank !

After debugging the issue, we managed to resolve it  by adding in the template.yaml under Globals/Api/BinaryMediaTypes this line   - application~1zip

We wanted to thank you for your fast responses and your time. You helped us narrowing the scope of possible solutions.

Thanks from my Team!

**Comment by slank** [comment]
Glad I could help, and glad you figured it out!
