### ISSUE TITLE
Wrong CONTENT_LENGTH when event.body contains non-ascii

### ISSUE THREAD

**Issue by mvanbaak** [slank/awsgi#43]
We run a flask application as lambda behind an api gateway using awsgi. This flask application reads the body as json with flasks request.get_json(). This bails out with a JSON error:
```Failed to decode JSON object: Expecting ',' delimiter: line X column Y (char Z)```

This is caused because awsgi sets the CONTENT_LENGTH in the environ to len(event.get('body', '')) but it should set it to the len of the encoded bytes string.

Call that works as expected:
``` curl -v -X PATCH -H 'Content-Type: application/json' http://127.0.0.1:3000/utf8test -d '{"test": "Jagermeister"}'```

Call that has this error as result:
``` curl -v -X PATCH -H 'Content-Type: application/json' http://127.0.0.1:3000/utf8test -d '{"test": "Jägermeister"}'```

**Comment by slank** [comment]
Hi, @mvanbaak. Thanks so much for putting in a fix for this. I'd like to maintain Python 2 compatibility at least until its EOL. Is it possible to fix your change to make it work with 2 and 3?

**Comment by mvanbaak** [comment]
Hey @slank. Sorry for the delay, but here it is.
The only change is using io.BytesIO for both python 2 and 3 (like it was before my changes)

**Comment by slank** [comment]
Thanks @mvanbaak, it's merged. I'll get a build out today.
