### ISSUE TITLE
super().__init__ can not be used in python2

### ISSUE THREAD

**Issue by Harpsichord1207** [slank/awsgi#48]
Hi, I used awsgi to deploy a flask app on AWS Lambda,  the run time is python2.7, then I got a type error:
```
Traceback (most recent call last):
  File "/var/task/app.py", line 19, in lambda_handler
    return awsgi.response(app, event, context, base64_content_types={"image/png"})
  File "/var/task/awsgi/__init__.py", line 169, in response
    return sr.response(output)
  File "/var/task/awsgi/__init__.py", line 91, in response
    rv = super().response(output)
TypeError: super() takes at least 1 argument (0 given)
```
so I edited the file as follows:

```
class StartResponse(object):  # use new-style class in python2
...
rv = super(StartResponse_GW, self).response(output)
...
rv = super(StartResponse_ELB, self).response(output)
```
so now it can work in python2.7

**Comment by slank** [comment]
Hi, @Harpsichord1207. Thanks for reporting this problem. Could you possibly submit a pull request for the change? That would help me a lot. If not, no problem! Just let me know and I'll add it to my to-do list.

As you may know, Python 2 is no longer supported by its maintainers. I think this is a small and innocuous enough fix, but I don't expect to spend any time to maintain Python 2 compatibility in the future. I strongly suggest you work to get your code compatible with Python 3.

**Comment by Harpsichord1207** [comment]
Hi @slank, I submitted a pull request to fix this issue, the code is just the same as I referred before, and I also added a unit test.

**Comment by slank** [comment]
Thanks! Merged. I'll cut a release later today.
