### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by slank** [slank/awsgi#68]
I'd like to humbly acknowledge that I have not actively maintained this project for some time. I don't expect my time commitments to change any time soon, so I'd like to ask for some interested parties to maintain and eventually take ownership.

If you have the time and patience to maintain `awsgi`, please use this issue to volunteer and discuss. Thanks.

**Comment by bipe15** [comment]
Like most people, I'm also kind of busy, but I would like to help to maintain this project ;)

**Comment by bipe15** [comment]
@slank Recently AWS launched [Lambda function URLs](https://docs.aws.amazon.com/lambda/latest/dg/lambda-urls.html?icmpid=docs_lambda_rss) which uses [Amazon API Gateway payload format version 2.0](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-format)

Fortunately, @c3ko has already developed the new format and a PR (#58) is waiting for merge. I'm my opinion, the new code does not break the format version 1.0. It would be nice if you merge that PR or give someone rights in the repo to do it (me for example :))
