### ISSUE TITLE
[ERROR] KeyError: 'httpMethod'

### ISSUE THREAD

**Issue by merajhasan88** [slank/awsgi#73]
Trying to integrate Flask with AWS Lambda through SAM. However, I am getting 404 Error when I hit the API.

Using `Windows`, with `Flask`, `awsgi`, `aws-cli` and `aws-sam`. Python `3.11`.

My `app.py`:
```
import awsgi
from flask import (
    Flask,
    jsonify,
)

app = Flask(__name__)


@app.route('/')
def index():
    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": "hello world",
            # "location": ip.text.replace("\n", "")
        }),
    }

def lambda_handler(event, context):
    return awsgi.response(app, event, context)
```

Steps to reproduce:
`sam build`

`sam deploy --guided`

`cURL  https://**********.execute-api.us-east-1.amazonaws.com/Prod/bot/`

Expected output"
`{ "message": "hello world"}`

What I get is `404 Error`.
If I run `sam remote invoke HelloWorldFunction --stack-name sam-flask`, I get:
```
Invoking Lambda Function HelloWorldFunction
START RequestId: e0d920ad-cc19-4292-bf69-a1d148bfc98e Version: $LATEST
[ERROR] KeyError: 'httpMethod'
Traceback (most recent call last):
  File "/var/task/app.py", line 21, in lambda_handler
    return awsgi.response(app, event, context)
  File "/var/task/awsgi/__init__.py", line 172, in response
    output = app(environ(event, context), sr)
  File "/var/task/awsgi/__init__.py", line 121, in environ
    'REQUEST_METHOD': event['httpMethod'],END RequestId: e0d920ad-cc19-4292-bf69-a1d148bfc98e
REPORT RequestId: e0d920ad-cc19-4292-bf69-a1d148bfc98e  Duration: 12.56 ms      Billed Duration: 13 ms  Memory Size: 128 MB     Max Memory Used: 63 MB  Init Duration: 557.31 ms
{"errorMessage": "'httpMethod'", "errorType": "KeyError", "requestId": "e0d920ad-cc19-4292-bf69-a1d148bfc98e", "stackTrace": ["  File \"/var/task/app.py\", line 21, in lambda_handler\n    return awsgi.response(app, event, context)\n", "  File \"/var/task/awsgi/__init__.py\", line 172, in response\n    output = app(environ(event, context), sr)\n", "  File \"/var/task/awsgi/__init__.py\", line 121, in environ\n    'REQUEST_METHOD': event['httpMethod'],\n"]}
```

I feel it is something simple I am missing.
If I replace `lambda_handler` with the tutorial code from AWS I get expected output.
This below is that code. So my AWS Lambda Proxy Resource is configured correctly for simple JSON but not for `awsgi`. 
```
def lambda_handler(event, context):
    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": "hello world",
            # "location": ip.text.replace("\n", "")
        }),
    }
```
What am I doing wrong? Can anyone help? I have been trying for a week now.

**Comment by kamil-korzeniak-mox** [comment]
Yo.

There is a mismatch between what is provided for awsgi.response() and what is expected by this lib.
While hitting a default route "/" its generating your error. To overcome this issue add below code just before your awsgi.response()

`    if event == {}:
        event['httpMethod'] = 'GET'
        event['path'] = '/'
        event['queryStringParameters'] = {}
        `

Adjust the dummy values as you want ;)

**Comment by merajhasan88** [comment]
> Yo.
> 
> There is a mismatch between what is provided by aws for awsgi.response() and what is expected by this lib. While hitting a default route "/" its generating your error. To overcome this issue add below code just before your awsgi.response()
> 
> ```
>  if event == {}:
>         event['httpMethod'] = 'GET'
>         event['path'] = '/'
>         event['queryStringParameters'] = {}
> ```
> 
> Adjust the dummy values as you want ;)

Thanks. I tried this and when I run `sam remote invoke HelloWorldFunction --stack-name sam-flask`, I get this response in prompt:
```
Invoking Lambda Function HelloWorldFunction
START RequestId: 0d8927a7-101b-46a1-b904-f82d582dda50 Version: $LATEST
END RequestId: 0d8927a7-101b-46a1-b904-f82d582dda50
REPORT RequestId: 0d8927a7-101b-46a1-b904-f82d582dda50  Duration: 17.54 ms      Billed Duration: 18 ms  Memory Size: 128 MB     Max Memory Used: 64 MB
{"statusCode": "200", "headers": {"Content-Type": "application/json", "Content-Length": "59"}, "isBase64Encoded": false, "body": "{\"body\":\"{\\\"message\\\": \\\"hello world\\\"}\",\"statusCode\":200}\n"}

This seems fine. However, when I run the API from the browser I get same 404 error. 
I tested in AWS Lambda and in `Execution Results` I got:
```
Response
{
  "errorMessage": "'httpMethod'",
  "errorType": "KeyError",
  "requestId": "a254165e-7f8f-43de-8f41-ea94e50053ae",
  "stackTrace": [
    "  File \"/var/task/app.py\", line 26, in lambda_handler\n    return awsgi.response(app, event, context)\n",
    "  File \"/var/task/awsgi/__init__.py\", line 172, in response\n    output = app(environ(event, context), sr)\n",
    "  File \"/var/task/awsgi/__init__.py\", line 121, in environ\n    'REQUEST_METHOD': event['httpMethod'],\n"
  ]
}

Function Logs
START RequestId: a254165e-7f8f-43de-8f41-ea94e50053ae Version: $LATEST
[ERROR] KeyError: 'httpMethod'
Traceback (most recent call last):
  File "/var/task/app.py", line 26, in lambda_handler
    return awsgi.response(app, event, context)
  File "/var/task/awsgi/__init__.py", line 172, in response
    output = app(environ(event, context), sr)
  File "/var/task/awsgi/__init__.py", line 121, in environ
    'REQUEST_METHOD': event['httpMethod'],END RequestId: a254165e-7f8f-43de-8f41-ea94e50053ae
REPORT RequestId: a254165e-7f8f-43de-8f41-ea94e50053ae	Duration: 20.45 ms	Billed Duration: 21 ms	Memory Size: 128 MB	Max Memory Used: 64 MB
```

I had rebuilt and redeployed. Would you happen to know why this is showing an error when API is hit or tested in Lambda?

**Comment by jackytsheng** [comment]
Hey, I had the same issue, i think it maybe because the event now used by [aws is 2.0](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-format)

in 2.0 these properties (eg: `httpMethod`) no longer exist directly under event. Instead they are now nested inside `requestContext.http` as per document suggested.

I haven't look too deep into how awsgi works, but by looking at the error code, i assume it expect format 1.0 event ?

While this could be something awsgi team may work on. I have an easy workaround for simply GET endpoint like `/ping`

```python
def handler(event, context):
    event['httpMethod'] = event['requestContext']['http']['method']
    event['path'] = event['requestContext']['http']['path']
    event['queryStringParameters'] = event.get('queryStringParameters', {})
    return awsgi.response(app, event, context) 
```
simply mapping the values before passing it to `awsgi.response`

hope this helps :)
