### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by blurrcat** [slank/awsgi#9]
Current pip release is lacking way back than master. Can we make a release some time soon? Thanks

**Comment by slank** [comment]
Hi, @blurrcat. Sorry for the delay. I should have CI set up soon and new versions will be automatically packaged.

**Comment by equake** [comment]
@slank do you want some help? how can I be useful? :)

**Comment by slank** [comment]
@equake I got sidetracked setting up the project in Travis and haven't gotten back to it. Sorry for the delay but I don't think there's anything I can hand off to you right away. I'll try to make some progress today.

**Comment by slank** [comment]
#8 Adds automated deployment for tagged commits and updates tests. @equake interested in reviewing?

**Comment by slank** [comment]
I'm reasonably confident in this and I'm going to go ahead and merge it. I'll do what I can to detect any post-deploy issues.

**Comment by slank** [comment]
I've _finally_ got Travis builds automated, so any new releases will automatically be built and deployed to PyPI. The current release is there now. Sorry for the delay.
